CREATE DATABASE IF NOT EXISTS wikifacts;
USE wikifacts;

CREATE TABLE IF NOT EXISTS users (
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    NAME VARCHAR(255) NOT NULL,
    HASH BINARY(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS scores (
    ID INT AUTO_INCREMENT PRIMARY KEY ,
    USERID INT NOT NULL,
    CORRECT INT NOT NULL,
    WRONG INT NOT NULL,
    CONFIDENCE INT NOT NULL
);

